// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Net.Protocol
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct Attack : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_12_19(); }
  public static Attack GetRootAsAttack(ByteBuffer _bb) { return GetRootAsAttack(_bb, new Attack()); }
  public static Attack GetRootAsAttack(ByteBuffer _bb, Attack obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public Attack __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public ulong ObjectId { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUlong(o + __p.bb_pos) : (ulong)0; } }
  public int Damage { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<Net.Protocol.Attack> CreateAttack(FlatBufferBuilder builder,
      ulong ObjectId = 0,
      int Damage = 0) {
    builder.StartTable(2);
    Attack.AddObjectId(builder, ObjectId);
    Attack.AddDamage(builder, Damage);
    return Attack.EndAttack(builder);
  }

  public static void StartAttack(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddObjectId(FlatBufferBuilder builder, ulong objectId) { builder.AddUlong(0, objectId, 0); }
  public static void AddDamage(FlatBufferBuilder builder, int damage) { builder.AddInt(1, damage, 0); }
  public static Offset<Net.Protocol.Attack> EndAttack(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Net.Protocol.Attack>(o);
  }
}


static public class AttackVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*ObjectId*/, 8 /*ulong*/, 8, false)
      && verifier.VerifyField(tablePos, 6 /*Damage*/, 4 /*int*/, 4, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
