// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Net.Protocol
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct Chat : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_12_19(); }
  public static Chat GetRootAsChat(ByteBuffer _bb) { return GetRootAsChat(_bb, new Chat()); }
  public static Chat GetRootAsChat(ByteBuffer _bb, Chat obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public Chat __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public Net.Protocol.ChatTypeId TypeId { get { int o = __p.__offset(4); return o != 0 ? (Net.Protocol.ChatTypeId)__p.bb.GetSbyte(o + __p.bb_pos) : Net.Protocol.ChatTypeId.TEXT; } }
  public ulong UserId { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetUlong(o + __p.bb_pos) : (ulong)0; } }
  public string Content { get { int o = __p.__offset(8); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetContentBytes() { return __p.__vector_as_span<byte>(8, 1); }
#else
  public ArraySegment<byte>? GetContentBytes() { return __p.__vector_as_arraysegment(8); }
#endif
  public byte[] GetContentArray() { return __p.__vector_as_array<byte>(8); }
  public long Timestamp { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }

  public static Offset<Net.Protocol.Chat> CreateChat(FlatBufferBuilder builder,
      Net.Protocol.ChatTypeId TypeId = Net.Protocol.ChatTypeId.TEXT,
      ulong UserId = 0,
      StringOffset ContentOffset = default(StringOffset),
      long Timestamp = 0) {
    builder.StartTable(4);
    Chat.AddTimestamp(builder, Timestamp);
    Chat.AddUserId(builder, UserId);
    Chat.AddContent(builder, ContentOffset);
    Chat.AddTypeId(builder, TypeId);
    return Chat.EndChat(builder);
  }

  public static void StartChat(FlatBufferBuilder builder) { builder.StartTable(4); }
  public static void AddTypeId(FlatBufferBuilder builder, Net.Protocol.ChatTypeId typeId) { builder.AddSbyte(0, (sbyte)typeId, 0); }
  public static void AddUserId(FlatBufferBuilder builder, ulong userId) { builder.AddUlong(1, userId, 0); }
  public static void AddContent(FlatBufferBuilder builder, StringOffset contentOffset) { builder.AddOffset(2, contentOffset.Value, 0); }
  public static void AddTimestamp(FlatBufferBuilder builder, long timestamp) { builder.AddLong(3, timestamp, 0); }
  public static Offset<Net.Protocol.Chat> EndChat(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Net.Protocol.Chat>(o);
  }
}


static public class ChatVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*TypeId*/, 1 /*Net.Protocol.ChatTypeId*/, 1, false)
      && verifier.VerifyField(tablePos, 6 /*UserId*/, 8 /*ulong*/, 8, false)
      && verifier.VerifyString(tablePos, 8 /*Content*/, false)
      && verifier.VerifyField(tablePos, 10 /*Timestamp*/, 8 /*long*/, 8, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
