// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Net.Protocol
{

public enum ChatTypeId : sbyte
{
  TEXT = 0,
  IMAGE = 1,
  SYSTEM = 2,
};


}
