// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Net.Protocol
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct Instantiate : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_12_19(); }
  public static Instantiate GetRootAsInstantiate(ByteBuffer _bb) { return GetRootAsInstantiate(_bb, new Instantiate()); }
  public static Instantiate GetRootAsInstantiate(ByteBuffer _bb, Instantiate obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public Instantiate __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public ulong ObjectId { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUlong(o + __p.bb_pos) : (ulong)0; } }
  public int PrefabId { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public Net.Protocol.Transform? ObjectTransform { get { int o = __p.__offset(8); return o != 0 ? (Net.Protocol.Transform?)(new Net.Protocol.Transform()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }

  public static Offset<Net.Protocol.Instantiate> CreateInstantiate(FlatBufferBuilder builder,
      ulong ObjectId = 0,
      int PrefabId = 0,
      Offset<Net.Protocol.Transform> ObjectTransformOffset = default(Offset<Net.Protocol.Transform>)) {
    builder.StartTable(3);
    Instantiate.AddObjectId(builder, ObjectId);
    Instantiate.AddObjectTransform(builder, ObjectTransformOffset);
    Instantiate.AddPrefabId(builder, PrefabId);
    return Instantiate.EndInstantiate(builder);
  }

  public static void StartInstantiate(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddObjectId(FlatBufferBuilder builder, ulong objectId) { builder.AddUlong(0, objectId, 0); }
  public static void AddPrefabId(FlatBufferBuilder builder, int prefabId) { builder.AddInt(1, prefabId, 0); }
  public static void AddObjectTransform(FlatBufferBuilder builder, Offset<Net.Protocol.Transform> objectTransformOffset) { builder.AddOffset(2, objectTransformOffset.Value, 0); }
  public static Offset<Net.Protocol.Instantiate> EndInstantiate(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Net.Protocol.Instantiate>(o);
  }
}


static public class InstantiateVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*ObjectId*/, 8 /*ulong*/, 8, false)
      && verifier.VerifyField(tablePos, 6 /*PrefabId*/, 4 /*int*/, 4, false)
      && verifier.VerifyTable(tablePos, 8 /*ObjectTransform*/, Net.Protocol.TransformVerify.Verify, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
