// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Net.Protocol
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct Packet : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_12_19(); }
  public static Packet GetRootAsPacket(ByteBuffer _bb) { return GetRootAsPacket(_bb, new Packet()); }
  public static Packet GetRootAsPacket(ByteBuffer _bb, Packet obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public static bool VerifyPacket(ByteBuffer _bb) {Google.FlatBuffers.Verifier verifier = new Google.FlatBuffers.Verifier(_bb); return verifier.VerifyBuffer("", false, PacketVerify.Verify); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public Packet __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public Net.Protocol.PacketHeader? Header { get { int o = __p.__offset(4); return o != 0 ? (Net.Protocol.PacketHeader?)(new Net.Protocol.PacketHeader()).__assign(o + __p.bb_pos, __p.bb) : null; } }
  public Net.Protocol.PacketPayload PayloadType { get { int o = __p.__offset(6); return o != 0 ? (Net.Protocol.PacketPayload)__p.bb.Get(o + __p.bb_pos) : Net.Protocol.PacketPayload.NONE; } }
  public TTable? Payload<TTable>() where TTable : struct, IFlatbufferObject { int o = __p.__offset(8); return o != 0 ? (TTable?)__p.__union<TTable>(o + __p.bb_pos) : null; }
  public Net.Protocol.ShowServerStats PayloadAsShowServerStats() { return Payload<Net.Protocol.ShowServerStats>().Value; }
  public Net.Protocol.Transform PayloadAsTransform() { return Payload<Net.Protocol.Transform>().Value; }
  public Net.Protocol.Instantiate PayloadAsInstantiate() { return Payload<Net.Protocol.Instantiate>().Value; }
  public Net.Protocol.Chat PayloadAsChat() { return Payload<Net.Protocol.Chat>().Value; }
  public Net.Protocol.MousePoint PayloadAsMousePoint() { return Payload<Net.Protocol.MousePoint>().Value; }
  public Net.Protocol.Attack PayloadAsAttack() { return Payload<Net.Protocol.Attack>().Value; }

  public static void StartPacket(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddHeader(FlatBufferBuilder builder, Offset<Net.Protocol.PacketHeader> headerOffset) { builder.AddStruct(0, headerOffset.Value, 0); }
  public static void AddPayloadType(FlatBufferBuilder builder, Net.Protocol.PacketPayload payloadType) { builder.AddByte(1, (byte)payloadType, 0); }
  public static void AddPayload(FlatBufferBuilder builder, int payloadOffset) { builder.AddOffset(2, payloadOffset, 0); }
  public static Offset<Net.Protocol.Packet> EndPacket(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Net.Protocol.Packet>(o);
  }
  public static void FinishPacketBuffer(FlatBufferBuilder builder, Offset<Net.Protocol.Packet> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedPacketBuffer(FlatBufferBuilder builder, Offset<Net.Protocol.Packet> offset) { builder.FinishSizePrefixed(offset.Value); }
}


static public class PacketVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Header*/, 20 /*Net.Protocol.PacketHeader*/, 4, false)
      && verifier.VerifyField(tablePos, 6 /*PayloadType*/, 1 /*Net.Protocol.PacketPayload*/, 1, false)
      && verifier.VerifyUnion(tablePos, 6, 8 /*Payload*/, Net.Protocol.PacketPayloadVerify.Verify, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
