// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Net.Protocol
{

public enum PacketPayload : byte
{
  NONE = 0,
  ShowServerStats = 1,
  Transform = 2,
  Instantiate = 3,
  Chat = 4,
  MousePoint = 5,
  Attack = 6,
};



static public class PacketPayloadVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, byte typeId, uint tablePos)
  {
    bool result = true;
    switch((PacketPayload)typeId)
    {
      case PacketPayload.ShowServerStats:
        result = Net.Protocol.ShowServerStatsVerify.Verify(verifier, tablePos);
        break;
      case PacketPayload.Transform:
        result = Net.Protocol.TransformVerify.Verify(verifier, tablePos);
        break;
      case PacketPayload.Instantiate:
        result = Net.Protocol.InstantiateVerify.Verify(verifier, tablePos);
        break;
      case PacketPayload.Chat:
        result = Net.Protocol.ChatVerify.Verify(verifier, tablePos);
        break;
      case PacketPayload.MousePoint:
        result = Net.Protocol.MousePointVerify.Verify(verifier, tablePos);
        break;
      case PacketPayload.Attack:
        result = Net.Protocol.AttackVerify.Verify(verifier, tablePos);
        break;
      default: result = true;
        break;
    }
    return result;
  }
}


}
