// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Net.Protocol
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct PacketHeader : IFlatbufferObject
{
  private Struct __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public void __init(int _i, ByteBuffer _bb) { __p = new Struct(_i, _bb); }
  public PacketHeader __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public Net.Protocol.PacketTypeId TypeId { get { return (Net.Protocol.PacketTypeId)__p.bb.GetUshort(__p.bb_pos + 0); } }
  public uint ConnectionId { get { return __p.bb.GetUint(__p.bb_pos + 4); } }
  public uint Timestamp { get { return __p.bb.GetUint(__p.bb_pos + 8); } }
  public ushort Sequence { get { return __p.bb.GetUshort(__p.bb_pos + 12); } }
  public ushort PayloadSize { get { return __p.bb.GetUshort(__p.bb_pos + 14); } }
  public ushort Checksum { get { return __p.bb.GetUshort(__p.bb_pos + 16); } }

  public static Offset<Net.Protocol.PacketHeader> CreatePacketHeader(FlatBufferBuilder builder, Net.Protocol.PacketTypeId TypeId, uint ConnectionId, uint Timestamp, ushort Sequence, ushort PayloadSize, ushort Checksum) {
    builder.Prep(4, 20);
    builder.Pad(2);
    builder.PutUshort(Checksum);
    builder.PutUshort(PayloadSize);
    builder.PutUshort(Sequence);
    builder.PutUint(Timestamp);
    builder.PutUint(ConnectionId);
    builder.Pad(2);
    builder.PutUshort((ushort)TypeId);
    return new Offset<Net.Protocol.PacketHeader>(builder.Offset);
  }
}


}
