// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Net.Protocol
{

public enum PacketTypeId : ushort
{
  PACKET_TYPE_NONE = 0,
  S2C_ShowServerStats = 10000,
  C2S_ShowServerStats = 10001,
  S2C_Transform = 20000,
  C2S_Transform = 20001,
  S2C_Instantiate = 20002,
  C2S_Instantiate = 20003,
  S2C_Chat = 20004,
  C2S_Chat = 20005,
  S2C_MousePoint = 20006,
  C2S_MousePoint = 20007,
  S2C_Attack = 20008,
  C2S_Attack = 20009,
};


}
