// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Net.Protocol
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct ShowServerStats : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_12_19(); }
  public static ShowServerStats GetRootAsShowServerStats(ByteBuffer _bb) { return GetRootAsShowServerStats(_bb, new ShowServerStats()); }
  public static ShowServerStats GetRootAsShowServerStats(ByteBuffer _bb, ShowServerStats obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public ShowServerStats __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public bool IsRunning { get { int o = __p.__offset(4); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }

  public static Offset<Net.Protocol.ShowServerStats> CreateShowServerStats(FlatBufferBuilder builder,
      bool IsRunning = false) {
    builder.StartTable(1);
    ShowServerStats.AddIsRunning(builder, IsRunning);
    return ShowServerStats.EndShowServerStats(builder);
  }

  public static void StartShowServerStats(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddIsRunning(FlatBufferBuilder builder, bool isRunning) { builder.AddBool(0, isRunning, false); }
  public static Offset<Net.Protocol.ShowServerStats> EndShowServerStats(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Net.Protocol.ShowServerStats>(o);
  }
}


static public class ShowServerStatsVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*IsRunning*/, 1 /*bool*/, 1, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
