// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Net.Protocol
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct Transform : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_12_19(); }
  public static Transform GetRootAsTransform(ByteBuffer _bb) { return GetRootAsTransform(_bb, new Transform()); }
  public static Transform GetRootAsTransform(ByteBuffer _bb, Transform obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public Transform __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public float PositionX { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public float PositionY { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public float PositionZ { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }

  public static Offset<Net.Protocol.Transform> CreateTransform(FlatBufferBuilder builder,
      float PositionX = 0.0f,
      float PositionY = 0.0f,
      float PositionZ = 0.0f) {
    builder.StartTable(3);
    Transform.AddPositionZ(builder, PositionZ);
    Transform.AddPositionY(builder, PositionY);
    Transform.AddPositionX(builder, PositionX);
    return Transform.EndTransform(builder);
  }

  public static void StartTransform(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddPositionX(FlatBufferBuilder builder, float positionX) { builder.AddFloat(0, positionX, 0.0f); }
  public static void AddPositionY(FlatBufferBuilder builder, float positionY) { builder.AddFloat(1, positionY, 0.0f); }
  public static void AddPositionZ(FlatBufferBuilder builder, float positionZ) { builder.AddFloat(2, positionZ, 0.0f); }
  public static Offset<Net.Protocol.Transform> EndTransform(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Net.Protocol.Transform>(o);
  }
}


static public class TransformVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*PositionX*/, 4 /*float*/, 4, false)
      && verifier.VerifyField(tablePos, 6 /*PositionY*/, 4 /*float*/, 4, false)
      && verifier.VerifyField(tablePos, 8 /*PositionZ*/, 4 /*float*/, 4, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
