// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Net.Protocol
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct TestTick : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_12_19(); }
  public static TestTick GetRootAsTestTick(ByteBuffer _bb) { return GetRootAsTestTick(_bb, new TestTick()); }
  public static TestTick GetRootAsTestTick(ByteBuffer _bb, TestTick obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public TestTick __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public byte RandomNumber { get { int o = __p.__offset(4); return o != 0 ? __p.bb.Get(o + __p.bb_pos) : (byte)0; } }

  public static Offset<Net.Protocol.TestTick> CreateTestTick(FlatBufferBuilder builder,
      byte randomNumber = 0) {
    builder.StartTable(1);
    TestTick.AddRandomNumber(builder, randomNumber);
    return TestTick.EndTestTick(builder);
  }

  public static void StartTestTick(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddRandomNumber(FlatBufferBuilder builder, byte randomNumber) { builder.AddByte(0, randomNumber, 0); }
  public static Offset<Net.Protocol.TestTick> EndTestTick(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Net.Protocol.TestTick>(o);
  }
}


static public class TestTickVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*RandomNumber*/, 1 /*byte*/, 1, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
